version: "3.9"
services:
  fluentbit:
    image: fluent/fluent-bit:2.1.10
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./scripts/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./logs:/app/logs
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/etc/grafana/demo-dashboards
      - grafana_data:/var/lib/grafana
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    logging:
      driver: fluentd
      options:
        tag: nginx
        fluentd-sub-second-precision: 'true'
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    volumes:
      - ./scripts/loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml
  
  api:
    build:
      context: .
      dockerfile: golang.Dockerfile
    ports:
      - "8080:8080"

volumes:
  grafana_data:
